### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by phuocle** [jordimontana82/fake-xrm-easy-js#1]
Any news? 1 year not see this repo update.

**Comment by jordimontana82** [comment]
Hi @phuocle,
yes, indeed, I know we were putting more efforts into the .net version but the intention is to gradually update this repo to cater for the new crm messages and the remaining web api operations

**Comment by jordimontana82** [comment]
Hi @phuocle, there have been quite many updates pushed into master yesterday... Loads of changes, basically framework has been rewritten to remove dependency on edge.js and it runs inside the node process only with 100% js code. (Previously it was js + .net code running and so performance wasn't great)

The project is now also way more easy to setup and run because of that (just npm run build & npm run test)


There is another repo (see below) with some samples. I'll be adding more examples next week.


https://github.com/jordimontana82/fake-xrm-easy-js-samples
